### ISSUE TITLE
Edit debug wiki page

### ISSUE THREAD

**Issue by mitchcapper** [dnSpyEx/dnSpy#106]
Should add COMPlus_JITMinOpts=1 ENV for .net core and the .ini files side by side does not work.  I also assume none of these are needed if the process is started with dnspy and CORDEBUG_JIT_DISABLE_OPTIMIZATION. 

I wrote a extension to generate the .ini files but as that doesn't work with .net core but assume it is actually not that useful given above.

**Comment by ElektroKill** [comment]
Hi, do you have a source for the `COMPlus_JITMinOpts` environment variable affecting the level of JIT optimization applied?

As for the `.ini` files, those are .NET Framework only.

**Comment by mitchcapper** [comment]
Yeah oddly no official source as probably primarily for internal use but:
- https://stackoverflow.com/questions/63959038/how-to-suppress-jit-optimization-in-net-core
- MS employee stating it: https://github.com/dotnet/runtime/issues/5767#issuecomment-216409312
- https://github.com/dotnet/runtime/blob/main/src/tests/JIT/opt/ObjectStackAllocation/ObjectStackAllocationTests.csproj - shows their official tests using that var
- https://github.com/dotnet/runtime/blob/main/src/coreclr/jit/jitconfigvalues.h - the vars themselves defined
- https://github.com/dotnet/runtime/blob/main/src/coreclr/vm/method.cpp#L3064-L3075 - used


Now maybe COMPlus_ZapDisable/COMPlus_ReadyToRun should take care of everything for .net core (https://docs.microsoft.com/en-us/archive/blogs/vancem/update-debugging-through-the-net-core-framework-v2-0-3-windows) but as `COMPlus_JITMinOpts` is called out a few places I figured I would mention it.

**Comment by ElektroKill** [comment]
I have updated the wiki page to include information about the `COMPlus_JITMinOpts` environment variable, INI files working only for .NET Framework, and that the additional steps mentioned on that page are not necessary when the dnSpy debugger starts the process.

Link to the page if you want to take a look at the new content: https://github.com/dnSpyEx/dnSpy/wiki/Making-an-Image-Easier-to-Debug

**Comment by mitchcapper** [comment]
wfm, i wrote a quick script to assist in setting debug env variables when unable to launch from the debugger.  It includes a couple more that might be useful
[dbg_launch.ps1.txt](https://github.com/dnSpyEx/dnSpy/files/9144039/dbg_launch.ps1.txt)
