### ISSUE TITLE
[Feature request] Copy IL codeinstruction as C# code

### ISSUE THREAD

**Issue by Neutron3529** [dnSpyEx/dnSpy#128]
I'm currently writing mods with help of dnSpyEx. Most of the cases, dnSpyEx works fine, but it is a little bit inconvenient that dnSpy could not copy IL code directly into the C# code format.

for example, I want to convert `ldc.i4.2` to `new CodeInstruction(OpCodes.Ldc_I4_2,null);`, and convert `call	int32 [UnityEngine.CoreModule]UnityEngine.Random::Range(int32, int32) ` to `new CodeInstruction(OpCodes.Call,typeof(UnityEngine.Random).GetMethod("Range",new Type[]{typeof(int),typeof(int)}/*, and maybe some BindingFlags here*/));`

Currently I convert them manually, But I would be apperciate if dnSpyEx could achieve these convert automatically.

Is it possible, or what I could help?

**Comment by ElektroKill** [comment]
Hi,
I do not plan on implementing such a feature. Implementing such a feature is a lot of work, especially when there are many .NET metadata editing libraries on the market like dnlib, cecil, or AsmResolver. Each of these has a slightly different API for editing method bodies which raises the question of which library we should use for such a feature or whether we should support all of them which would be a complicated and time-consuming thing to do. Furthermore, using reflection to retrieve members would not be applicable to this feature as we cannot just assume the user references the correct assemblies in their own project too. An implementation of this feature would have to build the references to members from scratch which can get complicated. I also do not think such a feature really makes sense in the regular releases in dnSpyEx. For now, I do not plan on implementing such a feature. Sorry!

This of course does not mean that you or someone else cannot make a dnSpyEx plugin that adds this functionality.

**Comment by Neutron3529** [comment]
> Each of these has a slightly different API for editing method bodies which raises the question of which library we should use for such a feature or whether we should support all of them which would be a complicated and time-consuming thing to do.

Is it possible to only support the basic `ILGenerator.Emit` support? Since `ILGenerator.Emit` is the official method, the best choice could be only support `ILGenerator.Emit` and generate something like `ILGenerator.Emit(OpCode, operand)`.

This is reasonable, since everyone could replace `ILGenerator.Emit` to their needs easily.

> Furthermore, using reflection to retrieve members would not be applicable to this feature as we cannot just assume the user references the correct assemblies in their own project too.

Most of the cases, modder have the whole project, which allow modder to reference any dll when they want to. Just show which dll is needed might be enough for dnSpyEx.

In the most rare case when dnSpyEx users must not reference some dll, write a tutorial to tell them what should do might be enough.

> This of course does not mean that you or someone else cannot make a dnSpyEx plugin that adds this functionality.

Is there any tutorial about write plugins for dnSpy?

Actually I'm a new C# user, I'm familar with C (and perhaps Rust), but not familar with C#. I learn C# IL first, and then learn most of the C# grammar from dnSpy. When I decide to write C# mod, I already switch my whole OS to Linux thus I have no idea how to install a MSVC.

As a result, I have no idea how to write such plugin.

Is there any tutorial about it?
