### ISSUE TITLE
Error while project exporting: The path is empty. (Parameter 'path')

### ISSUE THREAD

**Issue by kC0pter** [dnSpyEx/dnSpy#129]
Most likely an easy fix but i constantly get the error: The path is empty. (Parameter 'path')
This happens when i want to export as a Project.

Happens with all VS versions.

DNSpy version 6.2.0

**Comment by ElektroKill** [comment]
Hi, please provide a file which I can use to reproduce the problem.

**Comment by ElektroKill** [comment]
Due to the lack of response, I am unable to investigate this issue report. I am going to close this issue now. If you are still facing the problem and are able to provide a file I can use to reproduce this error, please reopen the issue.
