### ISSUE TITLE
Show IL opcode comments is not working

### ISSUE THREAD

**Issue by EDArthas** [dnSpyEx/dnSpy#134]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
 6.2.0
- Write down all steps needed to reproduce this issue. Also attach any needed files.
Option->Decompiler->IL->Show IL opcode comments is not working

**Comment by ElektroKill** [comment]
Hi, the IL opcode comments feature only works for the `IL` decompiler language. It also requires that you have .NET Framework 4 or newer installed on your system. The .NET Framework is needed for this feature as dnSpy extracts the comments from XML doc for the .NET Framework version of `mscorlib` assembly. Let me know if have these two prerequisites and if it still does not work.
