### ISSUE TITLE
Static event members cannot be analyzed to find who calls them 

### ISSUE THREAD

**Issue by xXTurnerLP** [dnSpyEx/dnSpy#137]
- What version did you use?
6.2.0

- Write down all steps needed to reproduce this issue. Also attach any needed files.
Here is a test dll: [test1.zip](https://github.com/dnSpyEx/dnSpy/files/9736881/test1.zip)
Open it with dnSpy and analyze `test1.class1.event1` member
You will not find who raised these events: 
![image](https://user-images.githubusercontent.com/40324267/194636929-fce036c7-c6c0-4278-baa9-ed4ad67ec2c7.png)

Here is the caller code from a test console app that calls the dll:
Output is "1234" followed by "1337"
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace testApp
{
	internal class Program
	{
		static void Main(string[] args)
		{
		        var a = new test1.Class1(0);
			a.testMethod3_this_should_be_detected();
			a.testMethod4_this_is_NOT_detected();
		}
	}
}
```

You can find more information about the bug on another fork of [dnSpy](https://github.com/VNGhostMans/dnSpyEx/issues/10) (because I opened the issue on the wrong repository, my dnSpy is downloaded from this repository so the bug applies to this repository specifically and probably to the other repository as well)

**Comment by ElektroKill** [comment]
Hi, I made some improvements to the "Raised By" analyzer relating to static events and accessibility analysis. Can you please test out the following build and see if your problem still persists?
Build link: https://github.com/dnSpyEx/dnSpy/actions/runs/3214134915

**Comment by xXTurnerLP** [comment]
Yes the build you linked works with static events, issue is solved on that build!
