### ISSUE TITLE
Add Vietnamese language

### ISSUE THREAD

**Issue by VNGhostMans** [dnSpyEx/dnSpy#138]
I provide you with the Vietnamese language files that I have translated (6.1.9)
[dnSpy Language Files (vi) RESX.zip](https://github.com/dnSpyEx/dnSpy/files/9741887/dnSpy.Language.Files.vi.RESX.zip)

**Comment by ElektroKill** [comment]
Hi, I will look through these language files and add them to dnSpy in the coming days.

**Comment by VNGhostMans** [comment]
@ElektroKill Please do [this](https://github.com/dnSpyEx/dnSpy/issues/28#issuecomment-1273406444)!
