### ISSUE TITLE
Cannot seem to debug using dnSpy

### ISSUE THREAD

**Issue by Xolzkatorf** [dnSpyEx/dnSpy#140]
I'm trying to debug an application using dnSpy but it says the debugger can't hit the code although this code being required to run. I've been looking for a solution but to no avail. If anyone has any tips it would be great.

**Comment by ElektroKill** [comment]
In order for me to provide further help, I would need to access the file you are trying to debug. It will also be required for you to provide more information about the issue you are facing. If this information is in regards to a file that is not meant to be accessed by the general public or contains sensitive information, we can move the conversation to email.
My email address: elektrokilldev@protonmail.com.

Thanks!

**Comment by ElektroKill** [comment]
Closing due to lack of further information provided
