### ISSUE TITLE
GitHub Actions artifacts huge in size

### ISSUE THREAD

**Issue by ElektroKill** [dnSpyEx/dnSpy#15]
It seems that after https://github.com/dnSpyEx/dnSpy/pull/13 was merged the artifacts have significantly grown in size. The .net core artifacts have gone from around 80MB to around 200MB and the .net framework artifact has gone from 20MB to 60MB. This is probably caused by the fact that GitHub actions doesn’t compress the artifacts or uses a different algorithm. This wasn’t a problem before as the compression was handled by powershell.

Goal: Find a way to shrink the artifacts in size so people with slower connections and or data caps have a easier time downloading dnSpySx.

**Comment by js6pak** [comment]
https://github.com/actions/upload-artifact/issues/39
tldr you can't have both single zip and compression, pretty sure zips you get from github actions artifacts are created without any compression at the fly by github web client.
imo just revert #13 and make releases instead

**Comment by TYoung86** [comment]
Maybe https://github.com/marketplace/actions/upload-a-build-artifact-as-is ?

**Comment by Nuklon** [comment]
Who cares about some extra MB? Surely the convenience of not having to open a zip in a zip is better :)

**Comment by ElektroKill** [comment]
I know it can be quite annoying to have a nested zip archive but I reverted the changes because I know some people who live in countries where ISP give them a data cap meaning they can only  download only X amount of bytes and upload Y amount. Making the output size smaller heavily benefits those people. Moreover, not everyone has extremely fast internet speeds so having a smaller file saves them a huge amount of time.

I will be looking at alternatives to hopefully keep both compression and a single zip but for now I wanted to make downloading dnSpyEx as easy and fast as possible. I haven’t had time to look into the alternative actions mentioned by TYoung86 but I will soon.

**Comment by riQQ** [comment]
This was 'fixed' in #90.

> It shows as the larger size, but downloads as the smaller.
