### ISSUE TITLE
reference issue 

### ISSUE THREAD

**Issue by drmasnavi** [dnSpyEx/dnSpy#150]
Hi every one.
I've got issue with compiling and saving my assembly.
since I'v installed dotnet 7 every time I try to build the final assembly latest version of system.linq or some other asms are automatically added to my project which is obvious in attachment. it's so confusing because the 7.0.0.0 version of it is not even loaded at all.
any comment?!
![RefProblem](https://user-images.githubusercontent.com/51479695/205470911-4886b1dc-8e1d-458a-9fb6-ce5866b7acea.png)

**Comment by ElektroKill** [comment]
Hi, I assume you are using the `Edit Method (C#)` feature to edit the contents of a .NET assembly.  The .NET assembly you are trying to edit is probably on an older .NET Core runtime version and for some reason, dnSpy incorrectly detects it as .NET 7. Would you mind providing me with this file you are trying to edit? You can do so either on GitHub or via e-mail: elektrokilldev@protonmail.com

Thanks!

**Comment by drmasnavi** [comment]
Thanks for reply. 
Sure I tried editing a method  of a dll which is targeting dotnet 6. the confusing part is that both system.linq 6.0  & 7.0 are added as references so base on arch. the 7.0 version is being loaded and make problem for running application.
the dll is in github:
https://www.nuget.org/packages/Abp.AspNetCore
I tried to change the default value of HeaderName as below:

namespace Abp.AspNetCore.Localization
public class AbpLocalizationHeaderRequestCultureProvider : RequestCultureProvider

-      public string HeaderName { get; set; } = CookieRequestCultureProvider.DefaultCookieName;
+	public string HeaderName { get; set; } = "-AspNetCore-Culture";

also I found a work around for my current patch but I'm worried about unintended consequences of such a behaviour for future projects.

kind regards

**Comment by ElektroKill** [comment]
Hi, I am unable to reproduce this problem. Please make sure you have a recent installation of the .NET 6 SDK on your system as otherwise, dnSpy will not be able to resolve assemblies properly!

**Comment by ElektroKill** [comment]
> Sure I’ve got the latest version of 6 & 7
I have both installed too.
> It looks like that I have to create a VM with just 6th version of dot net in order to be able to continue my projects.
This should not be necessary. dnSpy should resolve the proper version of depended assemblies if they are available. The only cause I can think of behind this incorrect version resolution is that the code to determine the target runtime of the file is producing an inaccurate result. Could you perhaps tell me whether the file you are currently editing is located in a directory with the name `net7.0` or `netstandard2.1` or similar? dnSpy uses these directory names to help determine the target runtime. If the directory does have the name following the format above please try moving the files to a different directory which does not follow that naming style and checking if you can still reproduce this bug.

Please let me know of the results!

**Comment by ElektroKill** [comment]
> the problem is just with system.linq which is fw library and is not being deployed to any folder and is resolved using GAC.

Yes, I understand the problem. However, System.Linq is not resolved using the GAC here. It is resolved from the .NET Core/.NET 5/6/7 installation directory where the runtime files for these frameworks are stored. The GAC (Global Assembly Cache) is only used for .NET Framework assemblies. In this case, we are dealing with a file targeting .NET 6.

> so I think the edit method after compile is not resolving assembly version of reference libraries. I have noticed that the system.linq v7 is not loaded automatically after loading the main dll. this file is just being added after saving the edited file.

dnSpy uses the same assembly resolution logic for both exploring assemblies and supplying the compiler with the dependency assemblies. The reason why the assembly is not loaded when exploring the file may just be the fact that it was not yet needed by the decompiler. The decompiler does not need to resolve as many assemblies as compared to the compiler as it has a lot of information to work off in the .NET metadata. The compiler, however, has to interpret just a bunch of text and it needs much more information and libraries to do that.

Back to the problem, the reason as to why I need to know the location of the file, which can be found in the root node decompilation, is that dnSpy uses the path to determine the target runtime of the assembly for assembly resolution:
![image](https://user-images.githubusercontent.com/37494960/208298915-a6ff2b6f-5978-4c17-98f0-83afc9f2ed7e.png)
In this case, there is no meaningful information in the path of the file. However, if the file was stored in a directory like `netstandard2.1` or `net7.0` (for example ` C:\Users\admin\Desktop\net7.0\Abp.AspNetCore.dll`) dnSpy can easily conclude that at runtime this assembly will be executed by the .NET 7 runtime and that runtime's dependency assemblies will be loaded. dnSpy takes this approach on assembly resolution as it needs to make sure it resolves the same files which are loaded at runtime to ensure seamless debugging. 

If the file you are trying to edit is located in such a directory it could explain the incorrect assembly resolution. This is why it is necessary for you to provide me with this information.

This is the only reason I can think of for the incorrect version of dependencies being resolved. The other ways of determining the target runtime work properly on this assembly and result in .NET 6.0 being the result. These methods have a lower priority than the full file path/location of the file.

**Comment by drmasnavi** [comment]
Base on your information I copied the dll to :
C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\6.0.11
and the problem got resolved;)
tnx a lot.
