### ISSUE TITLE
Settings doesn't saves properly

### ISSUE THREAD

**Issue by sunnamed434** [dnSpyEx/dnSpy#156]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
 v6.3.0-rc1

- Write down all steps needed to reproduce this issue. Also attach any needed files.
![image](https://user-images.githubusercontent.com/65300126/211010043-3465f60b-481f-4bf0-9938-7ce9b7ad5531.png)
After doing what on screenshot and relaunching the dnSpy, I've to set the settings again

**Comment by ElektroKill** [comment]
Hi, for me the settings save just fine. Are you sure there is no other process that is blocking access to the dnSpy config file located in `%APPDATA%\dnSpy\dnSpy.xml`?
![vmware_Ru0SGerQJy](https://user-images.githubusercontent.com/37494960/211011707-ed6efc64-89da-4b28-92ad-96fe3d5cf21a.gif)

**Comment by sunnamed434** [comment]
It is working fine after reinstalling dnSpy for net framework v6.3.0-rc1. Closing it, thanks for the help
