### ISSUE TITLE
dnSpy can't search decompile code

### ISSUE THREAD

**Issue by wrysunny** [dnSpyEx/dnSpy#157]
version : v6.2.0

I was amazed when I decompile a dll to search the code! You can see the method you want to search in the code window, but nothing is found in the assembly search.
what should I do? 
![image](https://user-images.githubusercontent.com/20748454/211997999-6a0ff401-0c9f-4245-b52a-79e7759a3e13.png)

**Comment by GazziFX** [comment]
Remove brackets `JavaScriptSerializer`

**Comment by wrysunny** [comment]
> 删除括号`JavaScriptSerializer`

does not work 😅
![image](https://user-images.githubusercontent.com/20748454/212002612-f744d1d6-4c29-4a9a-88b7-c11f08078efb.png)

**Comment by GazziFX** [comment]
Maybe its inside of dependency assembly which not loaded?

**Comment by wrysunny** [comment]
uh, what should I do? @GazziFX

**Comment by GazziFX** [comment]
Choose IL language it show assembly name
![image](https://user-images.githubusercontent.com/43498426/212007465-1afc5be7-c51e-44ce-8222-aa26801438b7.png)
![image](https://user-images.githubusercontent.com/43498426/212007643-94f9ec2e-0501-4a4d-803c-86a475e68dd3.png)

**Comment by wrysunny** [comment]
thanks @GazziFX

**Comment by ElektroKill** [comment]
Hi, does clicking on the `JavaScriptSerializer` type name in the decompiled code of `GetDic()` navigate to the decompiled code for `JavaScriptSerializer`? If clicking on the `JavaScriptSerializer` class does nothing, it means that dnSpy could not resolve the reference. This usually means that the assembly in which the type is located could not be found or that the assembly you are browsing is corrupted. It could also be a dnSpy bug.

Please try decompiling using the latest release candidate version, 6.3.0-rc2, and let me know your results. 
If nothing changes and you are still unable to click the `JavaScriptSerializer` to navigate to its decompilation then it means the assembly required to run this program is missing or is embedded inside the program by an obfuscator or a tool like Costura.Fody.

**Comment by wrysunny** [comment]
@ElektroKill  I uploaded a dll test file whose assembly is Dx.OfficeView. And update dnSpy to the latest version to try, click the type name in the decompiled code to navigate to the decompiled code
Now I want to search for the decompiled JavaScriptSerializer keyword, I'm sure there is this keyword after decompilation, but I can't search

[Dx.OfficeView.dll.zip](https://github.com/dnSpyEx/dnSpy/files/10407287/Dx.OfficeView.dll.zip)

**Comment by ElektroKill** [comment]
Hi, are you perhaps using the `feature/new-ilspy` branch? If so please do not use it for day to day use yet, it is very buggy and not close to being stable. Pleas e instead use stable builds from the master branch or official releases.

Also i downloaded your file and I am able to navigate to the `JavaScriptSerializer` class and the search component works as expected.
![image](https://user-images.githubusercontent.com/37494960/212379574-fd9cd0ee-e301-49a3-97bd-7db5ef70ea67.png)

![dnSpy_tdDhVo51nZ](https://user-images.githubusercontent.com/37494960/212379410-9df175a8-9df8-4feb-9e79-62367d3ce1d5.gif)

**Comment by wrysunny** [comment]
Thank you very much, solved my problem.
