### ISSUE TITLE
Follow convention for commits

### ISSUE THREAD

**Issue by oSumAtrIX** [dnSpyEx/dnSpy#161]
Currently, this repository is committed to with arbitrary commit messages. Following a convention allows to properly make and use commits purposefully, for example to generate a fully complete changelog automatically or to classify certain commit types consistently. Following a convention will greatly improve streamlined development.

RE: https://www.conventionalcommits.org/en/v1.0.0/, https://github.com/semantic-release/semantic-release.

**Comment by sunnamed434** [comment]
Good idea, also, added to my BitMono todos :) 👍

**Comment by ElektroKill** [comment]
This is a won't fix.

I prefer the current arbitrary commit messages over adding additional keywords to commit messages for benefits like changelog generators as I simply prefer to write those myself. Build processes are triggered automatically on every commit to producing pre-production builds already. Finally, I'd argue that slightly longer more detailed commit messages are easier to process for contributors and people working in the codebase than shorter ones including small tags. Sorry to disappoint but this is not a change I am planning to implement as it does not have that much benefit in my opinion for the amount of "getting used to" it would take!

**Comment by oSumAtrIX** [comment]
> Build processes are triggered automatically on every commit to producing pre-production builds already. 

Noting as a followup, by following standards it's possible to classify commits by type. Refactoring or chore commits for example will generate new pre-releases currently, when not required, but that is assumed to be negligible on contrast to your motivation points.
