### ISSUE TITLE
The `Assembly Explorer` cannot filter a single dragged item

### ISSUE THREAD

**Issue by Noisrev** [dnSpyEx/dnSpy#163]
This only works if you drag and drop two or more items.

Why not filter a single item? ~if (filenames.Length > 1)~

https://github.com/dnSpyEx/dnSpy/blob/f1f39e561b81a8f438450f9d4855c4e7781df44e/dnSpy/dnSpy/Documents/TreeView/DocumentTreeView.cs#L761-L769

Goto ***Options -> Assembly Explorer***, And set the ***Dragged items filter*** to **.NET only**.
- Drag and drop a txt file into the **Assembly Explorer**. It will be added.
- However, the filter will only work if you drag and drop two or more txt (or other) files.

**Comment by ElektroKill** [comment]
This is intended behavior. It is assumed that if the user drag and drops one file onto the assembly explorer, they want to open it no matter what. The filter is there to make opening entire directories of files easier an eliminate the loading of potentially unwanted files into the assembly explorer.
