### ISSUE TITLE
How can I export the project including the getter/setter name export?

### ISSUE THREAD

**Issue by thinhbuzz** [dnSpyEx/dnSpy#173]
- What version did you use?
> dnSpy v6.3.0

I can see the getter/setter name in the left sidebar but I can't get it in the editor view or the exported code. Please help

![image](https://user-images.githubusercontent.com/8065692/220543619-b8873b55-1ce3-4289-96c3-7b951039e949.png)
![image](https://user-images.githubusercontent.com/8065692/220543679-bad727d2-8eb9-4149-81d3-38271b87e773.png)

**Comment by ElektroKill** [comment]
Hi, 

The assembly explorer shows the raw method names found inside the metadata. The decompiler always tries to emit valid C# code. In C# property accessors methods are represented by the `get` and `set` keywords. In the metadata, these methods can have any name. In your image the `get` keyword refers to the method named `CENHMPMAAKB` and the `set` keyword refers to the method named `JLNBEOILGMN`. It's impossible to use these names in valid C# code.

**Comment by thinhbuzz** [comment]
@ElektroKill thanks for reply, I am looking for a way to get it on export, do you have any trick to do it

**Comment by ElektroKill** [comment]
> @ElektroKill thanks for reply, I am looking for a way to get it on export, do you have any trick to do it

How would you expect these methods to be represented as valid C#?

**Comment by thinhbuzz** [comment]
@ElektroKill it's nice to be able to get it like this, or any other way that makes it easy for us to know the method name
```c#
// Token: 0x170011A4 RID: 4516
// (get) Token: 0x06004C03 RID: 19459 RVA: 0x0001F410 File Offset: 0x0001D610
// (set) Token: 0x06004C84 RID: 19588 RVA: 0x00002053 File Offset: 0x00000253
[Token(Token = "0x170011A4")]
public double LNMLGIDEDPJ
{
	[Token(Token = "0x6004C03")]
	[Method(Name = "CENHMPMAAKB")]
	[Address(RVA = "0x2464528", Offset = "0x2464528", VA = "0x2464528")]
	get
	{
		return 0.0;
	}
	[Token(Token = "0x6004C84")]
	[Method(Name = "JLNBEOILGMN")]
	[Address(RVA = "0x2469C74", Offset = "0x2469C74", VA = "0x2469C74")]
	set
	{
	}
}
```
Or
```c#
// Token: 0x170011A4 RID: 4516
// (get) Token: 0x06004C03 RID: 19459 RVA: 0x0001F410 File Offset: 0x0001D610 Method Name CENHMPMAAKB
// (set) Token: 0x06004C84 RID: 19588 RVA: 0x00002053 File Offset: 0x00000253 Method Name JLNBEOILGMN
[Token(Token = "0x170011A4")]
public double LNMLGIDEDPJ
{
	[Token(Token = "0x6004C03")]
	[Address(RVA = "0x2464528", Offset = "0x2464528", VA = "0x2464528")]
	get
	{
		return 0.0;
	}
	[Token(Token = "0x6004C84")]
	[Address(RVA = "0x2469C74", Offset = "0x2469C74", VA = "0x2469C74")]
	set
	{
	}
}
```

**Comment by ElektroKill** [comment]
> ```cs
> // Token: 0x170011A4 RID: 4516
> // (get) Token: 0x06004C03 RID: 19459 RVA: 0x0001F410 File Offset: 0x0001D610
> // (set) Token: 0x06004C84 RID: 19588 RVA: 0x00002053 File Offset: 0x00000253
> [Token(Token = "0x170011A4")]
> public double LNMLGIDEDPJ
> {
> 	[Token(Token = "0x6004C03")]
> 	[Method(Name = "CENHMPMAAKB")]
> 	[Address(RVA = "0x2464528", Offset = "0x2464528", VA = "0x2464528")]
> 	get
> 	{
> 		return 0.0;
> 	}
> 	[Token(Token = "0x6004C84")]
> 	[Method(Name = "JLNBEOILGMN")]
> 	[Address(RVA = "0x2469C74", Offset = "0x2469C74", VA = "0x2469C74")]
> 	set
> 	{
> 	}
> }
> ```
Adding these custom attributes is not a good way to display such information in a decompiler. `MethodAttribute` is not a valid type in most contexts because it does not exist.


> ```cs
> // Token: 0x170011A4 RID: 4516
> // (get) Token: 0x06004C03 RID: 19459 RVA: 0x0001F410 File Offset: 0x0001D610 Method Name CENHMPMAAKB
> // (set) Token: 0x06004C84 RID: 19588 RVA: 0x00002053 File Offset: 0x00000253 Method Name JLNBEOILGMN
> [Token(Token = "0x170011A4")]
> public double LNMLGIDEDPJ
> {
> 	[Token(Token = "0x6004C03")]
> 	[Address(RVA = "0x2464528", Offset = "0x2464528", VA = "0x2464528")]
> 	get
> 	{
> 		return 0.0;
> 	}
> 	[Token(Token = "0x6004C84")]
> 	[Address(RVA = "0x2469C74", Offset = "0x2469C74", VA = "0x2469C74")]
> 	set
> 	{
> 	}
> }
> ```
Adding such information to the comments makes a bit of sense.

However, I still do not see a point in displaying such information in the exported project as the C# compiler is unable to reproduce such names when compiling the source code to a new assembly. Is there any specific reason as to why you need these names to be displayed in the decompiled code? These method names were created as a result of obfuscation applied to this file so they most likely do not mean anything.

**Comment by thinhbuzz** [comment]
@ElektroKill We have some work related to position + offset + method name, so I am looking for a solution to get method name. This feature may not be suitable for all businesses, but I would hope if it was built into dnSpy.

**Comment by ElektroKill** [comment]
I assume you are trying to perform further analysis on the assemblies produced by Cpp2IL or a similar project. If so, I strongly suggest analyzing these assemblies on the metadata level using libraries such as dnlib or AsmResolver to inspect the metadata of the files and extract all the information you may need. Analyzing source code is a very tedious task and can be very troublesome especially with obfuscated code and is also slower and less efficient. I don’t think that we should pollute the decompiled output with information that in 99% of use-cases is not considered useful.

**Comment by thinhbuzz** [comment]
@ElektroKill thank you, I fork and do it my way. but I still put this question up so if anyone needs it this will be a reference.
