### ISSUE TITLE
dnSpy's Tree View keeps re-focusing the assembly root, which brings recompilation of the entire module

### ISSUE THREAD

**Issue by ladislav-zezula** [dnSpyEx/dnSpy#175]
### Description

First of all, thanks for the continuous maintenance of this awesome tool.
* I am using version 6.3.0.0
* I am running it in a VMWARE machine in Windows 7 (32-bit)

I have a little issue with a ransomware sample.
* File SHA256: e4c2e0af462ebf12b716b52c681648d465f6245ec0ac12d92d909ca59662477b
* File link: https://www.virustotal.com/gui/file/e4c2e0af462ebf12b716b52c681648d465f6245ec0ac12d92d909ca59662477b
* Let me know if you can't download stuff from Virus Total, I'll send you the sample.

The sample is quite big. When load it into dnSpy, it decompiles it forever. This can be worked around when I select a function directly.

However, when I go debug the sample, dnSpy keeps focusing the main class, which again, brings the recompilation. So, I have to:
1) Do one step
2) Stop recompilation
3) Move to the current line manually.
4) Repeat

This becomes quite annoying after a few steps.

### Steps to reproduce

**Warning: The sample is a real working ransomware. Do NOT debug it unless it's in a virtual machine.**

1) Open the sample in dnSpy
2) Locale the entry point (`getActivationDataManualResetEvent.KeysOrderedAcrossPartitionsgetGenericParameterPosition.ReturnTypeIsCompatibilitySwitchSet`). You must do that manually, by locating the tree item. That way, you skip the endless decompilation.
3) Put a breakpoint to the first meaningful line (`if (KeysOrderedAcrossPartitionsgetGenericParameterPosition.CreateMessageSinkgetIsBrowserSave())`)
4) Debug the program (`F5`)
5) It should stop on that line

Now on every step (`F10`), you can notice that the tree view always moves to the root of the module (`getActivationDataManualResetEvent.KeysOrderedAcrossPartitionsgetGenericParameterPosition`). If the cursor stayed on the current function, I believe that the decompilation would not happen.

**Note that my problem is NOT the long decompilation**. Thats something that I just expect on those big samples.

**Comment by ElektroKill** [comment]
Hi,

Have you tried changing this option in the dnSpy settings? It's enabled by default.
![image](https://user-images.githubusercontent.com/37494960/222226701-b034ac56-d225-473b-b884-769d70ce6c78.png)

**Comment by ladislav-zezula** [comment]
Yes, I have that option checked. I also unchecked it and checked again to make sure that any setting would write through to the config. Unfortunately, dnSpy keeps focusing the root tree item and decompiling the whole class.

**Comment by ElektroKill** [comment]
> Yes, I have that option checked. I also unchecked it and checked again to make sure that any setting would write through to the config. Unfortunately, dnSpy keeps focusing the root tree item and decompiling the whole class.

Have you tried with the option unchecked?

**Comment by ladislav-zezula** [comment]
I can confirm that the opted-out setting works correctly and dnSpy does exactly what I want.
Sorry for my partial blindness.
