### ISSUE TITLE
Analyzing method produces wrong references

### ISSUE THREAD

**Issue by DarkerSquirrel** [dnSpyEx/dnSpy#176]
- What version did you use?
https://github.com/dnSpyEx/dnSpy/actions/runs/4286219146
- Write down all steps needed to reproduce this issue. Also attach any needed files.
[analyze_bug.zip](https://github.com/dnSpyEx/dnSpy/files/10863520/analyze_bug.zip)

1. select any method named n() or m() from Native.dll.Native.dll (as in screenshot)
2. click analyze
3. references produced are wrong , they point to different methods

**Comment by sunnamed434** [comment]
Are you sure? Might I got you wrong but I don't see a difference, and its kinda works fine, isn't it?

**Comment by ElektroKill** [comment]
Hi, what you are experiencing is intended behavior. When analyzing PInvoke method's dnSpy treats all methods with the same module name and entry point name as the same function. This is done to be more in line with how PInvoke functions work at runtime. In fact, `Native.dll` will only contain one `m` function and all the PInvoke methods with call that one function. The differences in signatures are used to make using functions from native assemblies easier in .NET and to inform the marshaller how to marshal the arguments passed in.

**Comment by DarkerSquirrel** [comment]
One thing I forgot to mention , sorry:

ILSpy's "Analyze"  correctly identifies references in this case.

Thanks

**Comment by ElektroKill** [comment]
> ILSpy's "Analyze" correctly identifies references in this case.
ILSpy's analyzer does a direct comparison of the references in the method bodies. dnSpy does this for regular bodies too but extends the search area and candidates for PInvoke methods to better simulate runtime behavior and export info the in the unmanaged file.
