### ISSUE TITLE
Debugger issue: Error: Value does not fall within the expected range.

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#181]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
6.3.0 release

- Write down all steps needed to reproduce this issue. Also attach any needed files.

just try to debug the exe:

got this error
```
[dnSpy]
Could not start the debugger. Make sure you have access to the file 'C:\tmp\Software_fix.exe'

Error: Value does not fall within the expected range.
```

Could you please add more details about the error, what value does it complain about?

PS I see that this error comes out from the routine named
void StartCore(CorDebugStartDebuggingOptions options) 
but it's in the else scope inside catch
at least would be nice to see the COM error code, cex.ErrorCode in the error message...

**Comment by greenozon** [comment]
Figured out the reason - the EP value inside the .exe was out of valid ranges...
you could edit any exe and see this error, so please consider the suggestion above
thanks!
feel free to close this issue

**Comment by ElektroKill** [comment]
Added in https://github.com/dnSpyEx/dnSpy/commit/d0a1feb9e33e30decc37b8e2a9d98ff8ea70b6b2
