### ISSUE TITLE
chatgpt

### ISSUE THREAD

**Issue by m1090c** [dnSpyEx/dnSpy#183]
can use chatgpt to use

**Comment by GazziFX** [comment]
What do you mean?

**Comment by sunnamed434** [comment]
ChatGPT chat in dnspy :D ?

**Comment by ElektroKill** [comment]
ChatGPT or any other machine learning/ai algorithm will not be implemented into the base version of dnSpy for the foreseeable future. I do not see it as something that fits into the project's aims and goals. However, you can make a separate dnSpy extension that adds AI integration into dnSpy in whatever way see fits :p
