### ISSUE TITLE
Internal error during stack trace exploring

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#184]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
dnSpy v6.3.0 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Debug an app,
during breakpoint try to double click on one of lines in the Call Stack panel

Following error appears:

![image](https://user-images.githubusercontent.com/765343/232693926-66b7d472-77f5-48a7-9f18-59beb4faafa6.png)

**Comment by ElektroKill** [comment]
Hi, could you provide the file you are working with? If you do not want to upload it to GitHub (some IP) then you can send it to me via email: elektrokilldev@protonmail.com

**Comment by greenozon** [comment]
sent out

**Comment by ElektroKill** [comment]
Hi, could you please see if the latest build available [here](https://github.com/dnSpyEx/dnSpy/actions/runs/4735381435/jobs/8405530996) fixes your issue?

**Comment by greenozon** [comment]
Issue fixed! error window is gone
kudos!
feel free to close this ticket
