### ISSUE TITLE
Idea: add new feature for anti-dbg detection

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#185]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
dnSpy v6.3.0 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.

Is it possible to add the CloseHandle anti-dbg feature into dnSpyEx support to mitigate debugger detection?
Current option is good enough for basic anti-debug, so thanks for that!
![image](https://user-images.githubusercontent.com/765343/233559036-32c1fcf6-c5ee-4cd7-9272-e4a0a0206b47.png)

I've seen the feature used for example by confuserex as well as others.. (vmp, etc)

```
				// CloseHandle
				try {
					CloseHandle(IntPtr.Zero);
				}
				catch {
					Environment.FailFast("");
				}
```

A description of above technology could be found for example over [here](https://anti-debug.checkpoint.com/techniques/object-handles.html#closehandle)

**Comment by ElektroKill** [comment]
Hi,

This is certainly something that is definitely possible. My current idea would be to hook `CloseHandle` and then in our hook call `NtQueryObject` with `ObjectHandleFlagInformation` as the information class. If this function returns a success HRESULT we can call the original `CloseHandle` but if it returns a failure HRESULT we can return `STATUS_INVALID_HANDLE`.

It sounds, easy but the implementation would have to be written purely in assembly for both target architectures (x86, x64) which can prove to be quite a challenge.

I will look into this further soon!

**Comment by ElektroKill** [comment]
Hi, I added a bypass for `CloseHandle` in commit https://github.com/dnSpyEx/dnSpy/commit/22ec81d6a626174bd21237ae39eab413dba3a279. Can you see if this works for you?

Link for CI build: https://github.com/dnSpyEx/dnSpy/actions/runs/4966350741

**Comment by ElektroKill** [comment]
Closing as resolved due to lack of a response.
