### ISSUE TITLE
Where is the Unity Mono Debugging thingy?

### ISSUE THREAD

**Issue by StupidRepo** [dnSpyEx/dnSpy#20]
I can't find the patched mono.dll in the Releases page or anything. Not even on the official dnSpy repo!

# PLEASE DON'T DIRECT ME TO THE DNSPY-UNITY-MONO REPO, I don't have time to build it myself!

I just need a build of mono.dll (patched) for Unity 2019.4.15f1

**Comment by ElektroKill** [comment]
I don't have the time to redirect you to the right place or create the downloads.

duplicate of #10

also if you're going to make a duplicate issue, which by the way you shouldn't do, at least be polite and act professional while doing it
