### ISSUE TITLE
VB decompiler produces exit for within while loops

### ISSUE THREAD

**Issue by nicolasj92** [dnSpyEx/dnSpy#212]
### dnSpyEx version

6.4.0

### Describe the Bug

The visual basic decompiler produces "Exit For" statements within while loops, leading to compilation errors. 

### How To Reproduce

Decompile an executable that contains while loops with exit conditions to visual basic

### Expected Behavior

The decompiler should produce "Exit While"

### Actual Behavior

The decompiler produces "Exit For"

**Comment by ElektroKill** [comment]
Hi, could you please provide a sample file that would allow me to reproduce this issue?

**Comment by nicolasj92** [comment]
Unfortunately I cannot upload the original program, but I will try to make a sample vb.net application

**Comment by ElektroKill** [comment]
Closing due to lack of response (a file which could be used to reproduce the program was not provided)!
