### ISSUE TITLE
I deleted the toolbar on the left to see the codes by mistake, is there any way to restore it I deleted the toolbar on the left to see the codes by mistake, is there any way to restore it

### ISSUE THREAD

**Issue by Kyros0175** [dnSpyEx/dnSpy#214]
### dnSpyEx version

6.4.0

### Describe the Bug

![Ảnh chụp màn hình 2023-06-25 195133](https://github.com/dnSpyEx/dnSpy/assets/136467644/b4e6a3b4-29c7-41ad-8b68-32ba23e3371e)

### How To Reproduce

.

### Expected Behavior

.

### Actual Behavior

.

**Comment by GazziFX** [comment]
Delete config in appdata

**Comment by puff** [comment]
Click View on the ribbon and then Assembly Explorer to restore it. Or press Ctrl+ Alt + L for a shortcut.

**Comment by Kyros0175** [comment]
Thank you!
