### ISSUE TITLE
Internal debugger error

### ISSUE THREAD

**Issue by t1a2l** [dnSpyEx/dnSpy#217]
### dnSpyEx version

6.4.0

### Describe the Bug

When I to see the result of this in watch "IEnumerable<string> newSpritesNames = newFiles.Select(x => x.name);"
I get the error in the title, clicking the button near it does nothing.
![image](https://github.com/dnSpyEx/dnSpy/assets/17047560/d5251345-39c1-4413-9873-1049c99e8a30)

### How To Reproduce

Try to create a IEnumerable<string> and see its result in the watch

### Expected Behavior

see twhat the list contains like anormal list

### Actual Behavior

Internal debugger error

**Comment by ElektroKill** [comment]
Closed due to lack of response
