### ISSUE TITLE
Add Azure Cloud Tests

### ISSUE THREAD

**Issue by pardeike** [dnSpyEx/dnSpy#224]
### Problem Description

Proposal: My open source project Harmony does testing in the cloud (Azure). My suggestion is to do the same especially since it allows you to use other environments. 

### Proposal

Check out https://github.com/pardeike/Harmony/blob/master/azure-pipelines.yml as a way to do matrix testing (arch x operating_system x net_version). It uses its companion template azure-pipelines-job-template.yml to do its job.

**Comment by ElektroKill** [comment]
Hi,

Currently, dnSpy does not have any unit tests or really any kind of automated testing at all. All changes are tested and verified manually, so there isn't really much we could run in the cloud regarding testing. dnSpy does, however, have CI build pipeline using GitHub Actions on a Windows runner to verify that the code pushed is buildable and I don't think that moving to Azure for that would have any benefits. If it would ever be necessary to build dnSpy on other platforms, GitHub Actions offers Linux and macOS runners as well.
