### ISSUE TITLE
CS0518: Predefined type 'System.Void' is not defined or imported

### ISSUE THREAD

**Issue by AceKiron** [dnSpyEx/dnSpy#228]
### dnSpyEx version

6.4.0

### Describe the Bug

dnSpyEx v6.4.0 can't even compile code that already exists in a DLL, let alone edited code.

### How To Reproduce

1) Open a DLL
2) Choose a method to edit
3) Rightclick and select "Edit Method (C#)..."
4) Click compile
5) Get a ton of errors

### Expected Behavior

I expected it to at least be able to compile its already existing code. I want to end up editing it, but that won't work either if this doesn't even work.

### Actual Behavior

I get a lot of the "CS0518: Predefined type 'System.Void' is not defined or imported" error.

### Additional Context

I tried both the latest release and the latest build.

**Comment by ElektroKill** [comment]
Hi, I cannot reproduce this error on my system with the files I have on hand. COuld you please provide the file you are trying to edit?

**Comment by AceKiron** [comment]
The issue was indeed missing the correct .NET Framework version.

**Comment by QiShangQuan** [comment]
这个问题怎么解决啊
