### ISSUE TITLE
Error CS0656 when attempting to modify asynchronous methods

### ISSUE THREAD

**Issue by rlaneth** [dnSpyEx/dnSpy#232]
### Description

I have encountered a problem while attempting to modify asynchronous methods using dnSpy. Initially, I aimed to edit and recompile an existing asynchronous method, which resulted in [Compiler Error CS0656](https://learn.microsoft.com/en-us/dotnet/csharp/misc/cs0656).

![Missing compiler required member 'AsyncUniTaskMethodBuilder<bool>.AwaitOnCompleted'](https://github.com/dnSpyEx/dnSpy/assets/10890823/22e725de-7cf6-4849-9ac4-3e5c25943882)

In an attempt to troubleshoot this issue, I decided to create a new bare-bones async method from scratch and integrate it into the targeted class. Unfortunately, I faced the same error consistently across all async methods that I attempted to either create or modify.

![Missing compiler required member 'System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitOnCompleted'](https://github.com/dnSpyEx/dnSpy/assets/10890823/a88bba45-2477-4fbc-aed8-35d58338cfff)

I'm curious whether this error stems from dnSpy lacking support for the modification of async methods, or if there might be a specific cause related to the application itself or my current setup.

Appreciate any insights in advance.

**Comment by ElektroKill** [comment]
Hi, the file you are looking at is compiled with Unity and thus uses Unity's implementation of the .NET runtime and its core libraries. Could you perhaps provide me with this file as well as all the other files next to `Assembly-CSharp.dll` (assuming you are editing this file) in the `Managed` folder? This would really help out as I would be able to reproduce this issue locally. if you are not comfortable with providing the files on GitHub you can email them to me, elektrokilldev@protonmail.com with the issue number in the title of the email!

For now, the best guess I have is that the C# compiler is expecting a core library member to be present when it is not in the Unity custom core libraries but I cannot say for sure without access to the file!

**Comment by rlaneth** [comment]
@ElektroKill Thanks for your quick response! I've sent you the email you requested.

**Comment by ElektroKill** [comment]
Hi, I took a look at your file, and the issue is indeed caused by the Roslyn compiler requiring the presence of `AwaitOnCompleted` method in custom async method builder types even if it will not be used when compiling an async method. The reason this method might not be present is either that the Unity C# compiler does not require it to be present or the types have been tampered with to remove the unused method. A solution to this problem would be to simply modify the async method builder types to include the `AwaitOnCompleted` method.

**Comment by rlaneth** [comment]
That makes a lot of sense. I've followed your suggestion and it worked. Thanks for having a look at this, even though in the end it wasn't actually a dnSpy issue!
