### ISSUE TITLE
unity mono binaries link leads to 404 page

### ISSUE THREAD

**Issue by SeleDreams** [dnSpyEx/dnSpy#233]
### dnSpyEx version

6.3.0

### Describe the Bug

the page of the repository seems to be outdated as https://github.com/dnSpyEx/dnSpy/releases/unity leads to a 404

### How To Reproduce

clicking on the link from the readme

### Expected Behavior

the link should lead to a proper page

### Actual Behavior

the link leads to a 404 page

**Comment by ElektroKill** [comment]
Hi,

Compiled versions of patched Unity Mono are no longer available for download. Please follow the instructions in the https://github.com/dnSpyEx/dnSpy-Unity-mono repository to compile an already pre-patched source code or patch a new version of Unity mono for your specific game.

The README has been updated to remove the mention of the Unity mono compiled binaries.

Sorry for the inconvenience!

**Comment by SeleDreams** [comment]
> Hi,
> 
> Compiled versions of patched Unity Mono are no longer available for download. Please follow the instructions in the https://github.com/dnSpyEx/dnSpy-Unity-mono repository to compile an already pre-patched source code or patch a new version of Unity mono for your specific game.
> 
> The README has been updated to remove the mention of the Unity mono compiled binaries.
> 
> Sorry for the inconvenience!

I've been experimenting on this level.
I tried to build the 2020.3.33f1 one but since the version of the game i build it for uses 2020.3.13, it doesn't seem to work (when I start the game, I quickly get the unity error reporting screen that pops and disappears and then nothing)
I guess I would need to build the one specific to 2020.3.13 however I don't know where to look for its source

**Comment by SeleDreams** [comment]
Ok, I found it, it's in the tags of the repository
![image](https://github.com/dnSpyEx/dnSpy/assets/16335601/c0c22e2d-0555-4ba0-a26f-8b13464fa78e)

**Comment by SeleDreams** [comment]
![image](https://github.com/dnSpyEx/dnSpy/assets/16335601/3d5ac4b1-bd86-44a0-9eff-614119845cf3)
One thing I noticed is that umpatcher was failing to update submodules, so I tried to check and it seems to be caused by some kind of error of github , that's pretty weird since i was able to clone the repository without issues

**Comment by SeleDreams** [comment]
I did the whole procedure, I patched the correct source, and then built it but I still end up with the issue.
One thing I noticed is that the file size of the output is lower than the file size of the original Unity one
![image](https://github.com/dnSpyEx/dnSpy/assets/16335601/1bf14cd9-2207-4bda-969d-efadd71e0ea9)
