### ISSUE TITLE
Incorrect decompilation when class and its namespace have the same name

### ISSUE THREAD

**Issue by MadProbe** [dnSpyEx/dnSpy#241]
### dnSpyEx version

6.3.0, 6.4.0

### Describe the Bug

There's a class in game's dll that has the same name of namespace its defined in and dnSpy decompiles the method where class name is referenced in the statement directly and using of the namespace doesn't help. It's quite annoying to add the missing namespace to mitigate the compilation error.

### How To Reproduce

1. Open attached Assembly-CSharp.dll
2. Go to global::CreatureUnit.OnClickByRoom(...)
3. Edit decompiled method.
4. Try to compile it.
5. Witness the error.

### Expected Behavior

Decompiled method should be recompilable without changing the code at all.

### Actual Behavior

It doesn't add the namespace.

### Additional Context

The DLL in ZIP file + other game DLLs for correct compilation without additional errors: 
[Assembly-CSharp.zip](https://github.com/dnSpyEx/dnSpy/files/12548081/Assembly-CSharp.zip)

**Comment by GazziFX** [comment]
Probably will be fixed with #5

**Comment by ElektroKill** [comment]
Hi,

Could you please test if the build available here fixes your issue? 
https://github.com/dnSpyEx/dnSpy/actions/runs/6126156199 (still building at the time of posting, should be done in a few minutes)

**Comment by MadProbe** [comment]
yep, that's fixed.
