### ISSUE TITLE
[Base Type and Interfaces] Loop

### ISSUE THREAD

**Issue by TheHellTower** [dnSpyEx/dnSpy#250]
### dnSpyEx version

6.4.1

### Describe the Bug

![dnSpy-x86_Sib9aO7JRT](https://github.com/dnSpyEx/dnSpy/assets/119943599/5570b7b1-4c47-4810-9753-6f35231a1a76)

### How To Reproduce

Add a Class that implement itself as Interface then expand the `Base Type and Interfaces`
![dnSpy-x86_5RMNrMHlb8](https://github.com/dnSpyEx/dnSpy/assets/119943599/618501b7-2f1e-4f5f-ba92-51679fd75c8d)

### Expected Behavior

![dnSpy_xQJiW4pPl0](https://github.com/dnSpyEx/dnSpy/assets/119943599/75b75b93-d798-4ef9-817a-38380ab141cc)

### Actual Behavior

Allow user to open in loop the interface if shown in the folder.

**Comment by ElektroKill** [comment]
Hi, I'd consider this intended behavior. dnSpy is correctly showing the looping inheritance structure found in your file. This inheritance structure is obviously invalid as `InterfaceImpl` rows should only point to interface types and not classes. It is also invalid that a type inherits from a static class like `<Module>`. These interface implementations are an artifact of obfuscation and should be removed during the deobfuscation process to comply with the ECMA-335 standard.
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/bfbc4583-9bb3-48e4-a5e7-ced9b679fd0b)

Changing the code to ignore these looping references will incorrectly show that they do not exist when they in fact do.
