### ISSUE TITLE
New assembled code is not the one being run while debugging

### ISSUE THREAD

**Issue by LoZio** [dnSpyEx/dnSpy#252]
### dnSpyEx version

6.4.1 32 bit

### Describe the Bug

I am patching an executable.
I have modified the code inserting new IL and NOPed other instructions.
I see my code in the decompile window as it should be.
I put a breakpoint before the modified code. Program stop when reaches the BP.
I step-over the code ad the newly assembled instructions are highlighted, as I expected.
The code that is run is the old code, not the actual one I see.
I need to close dnSpy and save the binaries, then reopen. I see the code as I patched it, but now it is run correctly as displayed.

### How To Reproduce

See steps above

### Expected Behavior

The code I see on the screen is the code being executed

### Actual Behavior

The current instruction line of the debugger runs over the new code, but the original one is run until clos>save>reopen

**Comment by ElektroKill** [comment]
The changes need to be actually saved to disk to be applied when debugging. Debugging just spawns a new process using the on-disk executable image. This is not a bug.
