### ISSUE TITLE
dnSpy-Unity-mono for version - 2021.3.29f1

### ISSUE THREAD

**Issue by xXTurnerLP** [dnSpyEx/dnSpy#255]
### Description

dnSpy-Unity-mono umpatcher doesnt support version 2021.3.29f1

**Comment by ElektroKill** [comment]
I do not currently provide support for Unity mono builds, you will need to fix it up for yourself. I don't have the required knowledge regarding Mono and Unity nor the time to maintain those builds. Sorry!
