### ISSUE TITLE
Question about renaming exe

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#259]
### Description

What is the right way to rename dnSpy exe file?
if I rename it say dnSpy-x86.exe -> dn6.exe and  dnSpy-x86.exe.config -> dn6.exe.config
then it wont start and generate the crash dump

the exception in dump will be:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'dnSpy, Version=6.4.1.0, Culture=neutral, PublicKeyToken=9813e10cffb0cdd6' or one of its dependencies. The system cannot find the file specified.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

at the same time  renaming dnSpy.exe + its config file will work fine...
kind of mystery..

**Comment by sunnamed434** [comment]
I think renaming it like that won't work, you to change <AssemblyName> in .csproj and recompile the solution

**Comment by ElektroKill** [comment]
dnSpy-x86 has a direct reference to dnSpy.exe/.dll (depending on whether the build is .NET Framework or .NET 6). If you want to rename both executables you will need to patch dnSpy-x86 and dnSpy with new assembly names and, in the case of dnSpy-x86, update the assembly reference to point to the correct executable. This can be done using dnSpy's high-level editor and PE properties editor (to update the assemblyref). However, the recommended way is to just recompile the project after renaming the two projects.

Hope this answers your question!

**Comment by greenozon** [comment]
Thanks
no easy way, but there is a way!
The question was raised as some tools started to kill dnSpy as part of anti-dbg strategy
