### ISSUE TITLE
Work not good with dynamic objects

### ISSUE THREAD

**Issue by CyanTailwinds** [dnSpyEx/dnSpy#26]
Hello I'm a very new C# learner, recently I wrote some demo code with dynamic objects, which I just learn.

But code in dnspy becomes very hard to read. 
"dynamic" becomes "object" and many lines about 
 dynamic object broken like "myclass_<>p50_<>o7"

I tried latest release but same
I tried latest ILSpy, the code is correct

I tried compare code between ilspy and dnspy , want to find something about it. But .sln is too big and too hard for me to read

So that's all I know, pls tell me if my issue is(maybe) a part of other one or it's already planned to fix

**Comment by ElektroKill** [comment]
Hello this is a known issue, dnSpy uses a very very old version of ILSpy decompiler. I’m working on upgrading dnSpy to the new ILSpy. Progress should be tracked by issue #5.
