### ISSUE TITLE
Double debugger question

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#264]
### dnSpyEx version

6.4.1 latest vanilla

### Describe the Bug

This is kind of tricky thing...
short description: 
I"m not able to debug x86 .net assembly if dnSpy(x86) was started under Olly2.01 debugger
for some reason it shows this:

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/51aad19d-cd76-4009-a5e8-638d3e48933a)

I"ve turned off all native anti-debug checks in Options as follows:
![image](https://github.com/dnSpyEx/dnSpy/assets/765343/3fd1f52b-6fe6-46db-b385-eba33cbed9c1)

my idea was to delegate it all to native debugger (basically to ScyllaHide anti-dbg plugin)

Now,
if I run the app in dnSpy *without* Olly2, the starts normally!!!

One might ask WTF double debugger?
but in some sense it makes sense as native dbg has bullet proof anti-dbg engine so the idea is to delegate native detection to native antidebug tools

### How To Reproduce

see above

### Expected Behavior

the app will successfully run in the above setup

### Actual Behavior

error above

### Additional Context

not sure what else is needed to push it forward?

**Comment by ElektroKill** [comment]
Using dnSpy and a different debugger at the same time is not possible. This is not a limitation of dnSpy but rather a limitation of the .NET CorDebug debugging API which will refuse to attach if a different debugger is already attached. If you want to achieve better anti-debug resistance, consider using the ScyllaHide injector together with dnSpy.

**Comment by greenozon** [comment]
Thanks for details and pointers!
