### ISSUE TITLE
Saved lists of programs

### ISSUE THREAD

**Issue by nekoboinick** [dnSpyEx/dnSpy#266]
### Problem Description

I would like to have the ability to save and load preset lists of binaries as I mod many different games, and I have found this program lags when there are numerous binaries loaded.

### Proposal

I would like to be able to save a list of programs and libraries to open later on the fly. I think the program should just mark whatever dll/exe or whatever that it cannot find as a missing, maybe with an outlined file icon or a question mark. Furthermore, I would prefer the preset file to be human-readable so that the paths to files could easily be changed with a script, in case of portable development environments.

### Alternatives

I don't really know of any other alternative other than maybe using something like Sandboxie to sandbox the settings into different file systems, kinda can't make an alternative for this, as far as I know. But, I would be happy to hear what any alternatives anyone else comes up with.

**Comment by ElektroKill** [comment]
Hi, sorry for the late response!

The functionality to keep lists of assemblies is already present. You can access it by going to the `File` menu.
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/01963245-fff4-430a-8aea-af296c1c793d)

The assemblies will by default go to the `(Default)` list. You can create a New list using the button. A new list with the provided name will be created. You can double-click it to open it and add assemblies to it. When you close dnSpy or switch to a different list the assemblies in that list will be stored in it to be accessed again later. The list information is stored in the dnSpy settings file which is encoded in XML. It is located in `%APPDATA%\dnSpy\dnSpy.xml`.
