### ISSUE TITLE
Turn off token/metadata comments

### ISSUE THREAD

**Issue by nxvvvv** [dnSpyEx/dnSpy#269]
### Description

Can the inclusion of metadata comments, such as `// Token: 0x0600000D RID: 13 RVA: 0x000023C0 File Offset: 0x000005C0`, be disabled? These comments appear in the exported code, adding an unnecessary step of manual removal and causing a time-consuming process. Are there any methods available to prevent these comments from being included during code export?

**Comment by ElektroKill** [comment]
These comments can be disabled in dnSpy settings. Please use the image attached as guidance on how to find and disable this option!
![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/162d8bd3-8904-499f-a789-85f50c287897)

Hope this resolves your issues!

**Comment by nxvvvv** [comment]
Thank you so much! That was it
