### ISSUE TITLE
can't find .exe

### ISSUE THREAD

**Issue by CorpseShadow67** [dnSpyEx/dnSpy#279]
### Description

I can't find the .exe

**Comment by SoNearSonar** [comment]
You can find the .exe [here on the releases page](https://github.com/dnSpyEx/dnSpy/releases/tag/v6.4.1), download any of the .zip files, extract the .zip file and you will see the .exe there

**Comment by ElektroKill** [comment]
https://github.com/dnSpyEx/dnSpy#binaries
