### ISSUE TITLE
Vietnamse Language

### ISSUE THREAD

**Issue by VNGhostMans** [dnSpyEx/dnSpy#28]
Please add this Vietnamese language pack. I have finished translating it. Thanks
[dnSpy Language Files (vi) RESX.zip](https://github.com/dnSpyEx/dnSpy/files/7070214/dnSpy.Language.Files.vi.RESX.zip)

**Comment by ElektroKill** [comment]
Can you please open this in the form of a pull request?

**Comment by VNGhostMans** [comment]
@ElektroKill I mean delete this issues forever

**Comment by VNGhostMans** [comment]
Hi, can you delete this issue and this [issue](https://github.com/dnSpyEx/dnSpy/issues/27)? Because it's too much of a duplication!
