### ISSUE TITLE
When trying to edit anything that is Async it throws error code CS0656

### ISSUE THREAD

**Issue by DxtrPog** [dnSpyEx/dnSpy#283]
### dnSpyEx version

6.4.1

### Describe the Bug

I am trying to mod a Unity project and one of the parts I am trying to change uses Async, all I am trying to do is change a single word but it is unable to build, when built it throws error code CS0656 and says "Missing compiler required member 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AwaitOnCompleted'"

### How To Reproduce

Find a Unity Project with asynchronous code and try to edit it :3

### Expected Behavior

Compiles and edits the text

### Actual Behavior

Throws error code CS0656 and says "Missing compiler required member 'System.Runtime.CompilerServices.AsyncTaskMethodBuilder.AwaitOnCompleted'"

**Comment by ElektroKill** [comment]
See https://github.com/dnSpyEx/dnSpy/issues/232 for more information
