### ISSUE TITLE
Add Save code in File Menu

### ISSUE THREAD

**Issue by gagmeng** [dnSpyEx/dnSpy#29]
It is recommended to add save code in file menu in the new version, This function has been implemented in the previous V4.5, but  now it has been deleted.

**Comment by ElektroKill** [comment]
What would this option do exactly? Do you mean saving the raw IL bytes of a method from the original PE stream?

**Comment by gagmeng** [comment]
> What would this option do exactly? Do you mean saving the raw IL bytes of a method from the original PE stream?

It means save one class to the .cs file.

**Comment by ElektroKill** [comment]
Hi, looks like this feature was removed by 0xd4d in commit https://github.com/dnSpyEx/dnSpy/commit/6ca9aabb3199489475d91e7c8c98ddab28ad29ee. I have no idea to be completely honest. I will see if adding this back requires any significant changes and if not I will get it done ASAP.
