### ISSUE TITLE
Drag and drop to file to editor not working fo x86 netframework version

### ISSUE THREAD

**Issue by ewwink** [dnSpyEx/dnSpy#291]
### dnSpyEx version

6.5.0 rc3

### Describe the Bug

I cannot drop any file to x86 editor

### How To Reproduce

drag and drop exe or dll from windows explore to editor

### Expected Behavior

File should be in assembly explorer like in x64 version

### Actual Behavior

nothing dropped to assembly explorer

**Comment by ElektroKill** [comment]
I cannot reproduce the issue you are facing. When I drag and drop a .exe file onto dnSpy-x86 from the netframework distribution of 6.5.0-rc3, it appears in the assembly explorer without issues. Make sure you are NOT running dnSpy as administrator though. Running applications as Administrator interferes with the drag-and-drop functionality (this is a known windows issue).

**Comment by ewwink** [comment]
you are right, `Running as Administrator` causing the problem, uncheck the option and it now working.

Thank you 

![image](https://github.com/dnSpyEx/dnSpy/assets/760764/16cc6e53-343c-4910-897e-f1298f99e721)

**Comment by ewwink** [comment]
Reopening, if not run as administrator we cannot do debugging, can it prompt user to automatically re-launch the app as administrator?

**Comment by ElektroKill** [comment]
> Reopening, if target app require admin right we cannot debug, can it prompt user to automatically re-launch the app as administrator?

I've added an option in the `File` menu to restart dnSpy as administrator. If the debugger states this is necessary, you can now use this option.

**Comment by Deltafox79** [comment]
> > Reopening, if target app require admin right we cannot debug, can it prompt user to automatically re-launch the app as administrator?
> 
> I've added an option in the `File` menu to restart dnSpy as administrator. If the debugger states this is necessary, you can now use this option.

Not work on Net 8.0 Release x64/x86

Regards
