### ISSUE TITLE
Release log for 6.5.0 corrections

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#292]
### dnSpyEx version

6.5.0

### Describe the Bug

Is it possible to correct the 1st statement? 

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/204779f0-d731-4282-a12c-00de539abe48)

it sounds a bit risky and it fact is not true, for example:
it's absolutely easy and legally without any hacks to install .NET 8 and run build 6.5.0 on Windows 7:

![image](https://github.com/dnSpyEx/dnSpy/assets/765343/4e0479d3-acd5-4484-9db4-10c77944e8cb)

thus I propose to correct the 1st statement
thanks

### How To Reproduce

-

### Expected Behavior

-

### Actual Behavior

-

### Additional Context

-

**Comment by ElektroKill** [comment]
Hello!

That is very interesting! I based that line on the official .NET 8 documentation which states that Windows 11, and Windows 10 are only supported non server operating systems! Perhaps this is not true for self-contained .NET 8 applications.
https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md

I will correct this information now.

Thanks for the information!
