### ISSUE TITLE
System.OverflowException Error

### ISSUE THREAD

**Issue by cmot17** [dnSpyEx/dnSpy#30]
- What version did you use?
6.1.9
- Write down all steps needed to reproduce this issue. Also attach any needed files.
This just happens at random times for me - nothing that I do makes it happen, just shows up occasionally.
![image](https://user-images.githubusercontent.com/25753364/133891764-8a56d55d-71ce-43a6-8b80-c5da3ddd7eb0.png)

Attached is the file that the issue has been occurring on, although I don't know if that has anything to do with the issue as I haven't really decompiled other files.
[Assembly-CSharp.zip](https://github.com/dnSpyEx/dnSpy/files/7190057/Assembly-CSharp.zip)

**Comment by ElektroKill** [comment]
I'm not able to reproduce this issue (tested on many computers with different windows versions). It seems as this exception happens deep in the .NET runtime, so I can't tell if this is a dnSpy issue in the first place.

**Comment by ElektroKill** [comment]
Closed to to lack of activity
