### ISSUE TITLE
Update to ilspy 8.2

### ISSUE THREAD

**Issue by gagmeng** [dnSpyEx/dnSpy#310]
### Problem Description

![image](https://github.com/dnSpyEx/dnSpy/assets/13564117/8f778ae7-c245-4002-8240-c22e50b21f3c)

### Proposal

![image](https://github.com/dnSpyEx/dnSpy/assets/13564117/b0e72926-4251-4d90-a11e-9c0c5ba88269)

**Comment by ElektroKill** [comment]
Duplicate of #5.
