### ISSUE TITLE
ICSharpCode Decompiler DecompilerException on dnspy net8 of 28 April 2024

### ISSUE THREAD

**Issue by Deltafox79** [dnSpyEx/dnSpy#321]
### dnSpyEx version

6.5.0 NET 8

### Describe the Bug

ICSharpCode.Decompiler.DecompilerException

### How To Reproduce

Just Open a dll

Bug is not present on net4.8 Framework...

### Expected Behavior

[XmlElement(Namespace = "http://schemas.datacontract.org/2004/07/System")]
	public byte _XXX
	{
		get
		{
			....
		}
		set
		{
			....
		}
	}

### Actual Behavior

[XmlElement(Namespace = "http://schemas.datacontract.org/2004/07/System")]
	public byte _XXX
	{
		get
		{
			/*
An exception occurred when decompiling this method (060001C5)

ICSharpCode.Decompiler.DecompilerException: Error decompiling System.Byte ......

 ---> System.InsufficientExecutionStackException: Insufficient stack to continue executing the program safely. This can happen from having too many functions on the call stack or function on the stack using too much stack space.
   at ICSharpCode.Decompiler.StackOverflow.Prevent() 
.....
*/;

**Comment by ElektroKill** [comment]
Oh my! I made a terrible typo in commit https://github.com/dnSpyEx/dnSpy/commit/518fa2ffaceffab59b29fb5f1d456d3587bc4257.

The if statement in the ICSharpCode.Decompiler project and the if statement in the debugger projects should be inverted. (They are missing a `!`) I can’t believe I missed this.

I’m currently away from home without a pc for a week so I will see what i can do using a mobile iOS device 😅
