### ISSUE TITLE
.dat file 

### ISSUE THREAD

**Issue by Dwisantosobk** [dnSpyEx/dnSpy#328]
### Description

![image](https://github.com/dnSpyEx/dnSpy/assets/86861327/570e41a6-d571-4223-b02a-9b832302eb88)

hi can someone tellme how to open .dat file

**Comment by GazziFX** [comment]
Extension doesnt mean, it can be anything, save it and use other detection programs

**Comment by ElektroKill** [comment]
There is no one format a `.dat` file can take. The format of a `.dat` file typically depends on the program consuming it. I suggest you analyze this program and how it uses its resources to find out what format the data is and how to interpret it. Alternatively, you can extract the resource and try to run it through some file format detection software as mentioned by @GazziFX.

Closing this as it is out of scope for dnSpy.

**Comment by Dwisantosobk** [comment]
> Extension doesnt mean, it can be anything, save it and use other detection programs

Can u tell me

**Comment by Dwisantosobk** [comment]
> There is no one format a `.dat` file can take. The format of a `.dat` file typically depends on the program consuming it. I suggest you analyze this program and how it uses its resources to find out what format the data is and how to interpret it. Alternatively, you can extract the resource and try to run it through some file format detection software as mentioned by @GazziFX.
> 
> Closing this as it is out of scope for dnSpy.

Can u tell me sir
