### ISSUE TITLE
dnSpy.Console.exe not working since dnSpy 6.1.8 (dnSpy) / 6.1.9 (dnSpyEx)

### ISSUE THREAD

**Issue by uniquoo** [dnSpyEx/dnSpy#33]
For both versions:

- Last on dnSpy (6.1.8) 
- Latest on dnSpyEx (6.1.9)

the console client is not working. 6.1.7 is working fine.

**Comment by ElektroKill** [comment]
Hi, please try using the latest build available here: https://github.com/dnSpyEx/dnSpy/actions/runs/1242780074

**Comment by uniquoo** [comment]
> Hi, please try using the latest dev build available here: https://github.com/dnSpyEx/dnSpy/actions/runs/1242780074

That is not working either. It executes but seems to die:

```
C:\Users\uq\Desktop\test>dnSpy.Console.exe -h
C:\Users\uq\Desktop\test>dnSpy.Console.exe -v
C:\Users\uq\Desktop\test>dnSpy.Console.exe
```

**Comment by ElektroKill** [comment]
Are you using the .NET 5.0 or the .NET framework release?

**Comment by uniquoo** [comment]
> Are you using the .NET 5.0 or the .NET framework release?
![gg](https://user-images.githubusercontent.com/970999/134803807-44d50c73-4af3-49ba-acbc-447e3faa0856.PNG)

**Comment by ElektroKill** [comment]
I'm asking which download of dnSpyEx did you use. There are both .NET Framework and .NET 5 downloads available :)

**Comment by uniquoo** [comment]
Neither works.

**Comment by ElektroKill** [comment]
@uniquoo Hi, could you test the latest available build (https://github.com/dnSpyEx/dnSpy/actions/runs/1596499023). I've updated to the .NET 6.0 SDK and I'm interested in whether that fixed your problem.

**Comment by uniquoo** [comment]
> @uniquoo Hi, could you test the latest available build (https://github.com/dnSpyEx/dnSpy/actions/runs/1596499023). I've updated to the .NET 6.0 SDK and I'm interested in whether that fixed your problem.

I can also confirm this build working. Thanks for keeping me in the loop. Issue can be marked solved now.

**Comment by qux-bbb** [comment]
The files on https://github.com/dnSpyEx/dnSpy/actions/runs/1596499023 are Expired.

**Comment by ElektroKill** [comment]
If you would like to use a build that contains the fix, you can find the download link to the latest bleeding edge beta build in the readme file.

**Comment by qux-bbb** [comment]
> If you would like to use a build that contains the fix, you can find the download link to the latest bleeding edge beta build in the readme file.

Thanks!
