### ISSUE TITLE
Save Module progress indicator may not appear if computer is too fast

### ISSUE THREAD

**Issue by 8749236** [dnSpyEx/dnSpy#336]
### dnSpyEx version

6.5.1

### Describe the Bug

The progress indicator of Save Module dialog closes immediately when completed, but the progress indicator may not appear at all if computer is way too fast. (E.g. 14700k + 2x32GB 7200MHz + small program)

### How To Reproduce

1. (Optional) Build a very fast computer with very high score
2. Open a small C# program with dnSpyEx 6.5.1
3. Make any changes to the program.
- Add or delete a resource
- Find a class and edit its source code
- etc.
4. File -> Save Module -> Ok
5. The progress indicator may or may not appears, since the processing takes less time for UI to appear, and UI gets closed before it can be displayed.
6. Open file property and observe its modified date has been changed.

### Expected Behavior

The progress indicator should contain a button for dismissing it when progress bar is full, it should let user acknolwedge the completion then dismiss itself.
It should have a checkbox for auto dismissing in the future.
In options menu, there should be an option to disable auto dismissing.

### Actual Behavior

The progress indicator may or may not appear.
When it appears, it closes itself immediately when progress bar is full, if user isn't paying attention, then they don't know whether the operation is finished.
When it doe not appear, there is no other feedback on whether the action actually took place.

Alternative is add a status bar and throw a prompt there. Example of VS2022's save prompt.
![image](https://github.com/dnSpyEx/dnSpy/assets/5711854/39d379c3-9e81-40a2-98a1-f32844481e48)

**Comment by ElektroKill** [comment]
Hi,

Sorry for the late response.

What do you think of adding an artificial delay to the dialog closing of 250ms, that is if the save operation completes the dialog will stay open for at least 250ms even if the saving was faster? If the saving operation takes longer, no delay will be in effect.

This should be relatively easy to implement.

Let me know what you think!

**Comment by 8749236** [comment]
250ms is fine and probably easiest to implement.

ElektroKill ***@***.***> 于 2024年7月31日周三 上午5:22写道：
