### ISSUE TITLE
Add "Exclude All Framework Assemblies" in search

### ISSUE THREAD

**Issue by gagmeng** [dnSpyEx/dnSpy#338]
### Problem Description

![image](https://github.com/dnSpyEx/dnSpy/assets/13564117/b2fa198f-63df-45c1-a125-c48cfb52df5d)

### Proposal

Just as note in problem description.

**Comment by ElektroKill** [comment]
Hello, this option already exists.

Click on the options drop down and the following checkboxes will appear. Here you will a checkbox that controls searching framework assemblies.

![image](https://github.com/dnSpyEx/dnSpy/assets/37494960/2250c674-b7c1-4c5e-8d16-8c4497c8f6ab)

Hope this helps!
