### ISSUE TITLE
ilspy new branch - OpCode not supported: LdMemberToken

### ISSUE THREAD

**Issue by Nuklon** [dnSpyEx/dnSpy#34]
- What version did you use?
Latest commit from ilspy new branch.
- Write down all steps needed to reproduce this issue. Also attach any needed files.
Some assemblies now get this error in decompiled text: OpCode not supported: LdMemberToken.
The assembly works in master branch.

**Comment by ElektroKill** [comment]
Known issue, that branch is currently highly work in progress. Will be fixed as soon as I can! Colors in decompiler as well as debugger support will also be resolved together with other stuff that differs from the master branch. Currently development has slowed down as school has started for me :/

**Comment by Nuklon** [comment]
Ah, alright, no problem 👍 Thought I'd report it in case you weren't aware.

**Comment by ElektroKill** [comment]
This has been fixed.
