### ISSUE TITLE
How could I add dll files as dependencies?

### ISSUE THREAD

**Issue by ShoelessTom** [dnSpyEx/dnSpy#359]
### Description

![image](https://github.com/user-attachments/assets/53e2ffd1-6b84-4f8d-88c7-710239246eaa)
For example, if I have a dll file I want to add to this thing, how can I do so. or is this not possible? 
Alot of programs I want to decompile and edit require me to add some missing dependencies to compile the edited version.
So my question is is there a way to do so or is there no way to add dependencies?

**Comment by ElektroKill** [comment]
Hi, this can be done when editing using the C# edit dialog.

![image](https://github.com/user-attachments/assets/90ffc057-7212-4c77-9f2e-cf54912108ca)

This button shown in the image allows the selection of an arbitrary DLL on the disk while the button next to it allows the selection of an assembly from the GAC which includes the basic framework assemblies.
