### ISSUE TITLE
A project for decompiling a single exe file

### ISSUE THREAD

**Issue by fanbook-wangdage** [dnSpyEx/dnSpy#360]
### Problem Description

When selecting to generate a single file at the time of release, decompilation does not work properly.  

---

反编译单个exe的项目  
发布时选择生成单个文件，此时无法正常反编译

### Proposal

Supports decompiling a single exe project

---

支持反编译单个exe项目

### Additional Context

![image](https://github.com/user-attachments/assets/a6253103-91a0-49ea-bb9e-b7941836da2f)

**Comment by GazziFX** [comment]
Try this branch https://github.com/dnSpyEx/dnSpy/tree/feature/single-file-bundles
