### ISSUE TITLE
Find references for a specific enum value

### ISSUE THREAD

**Issue by Symbai** [dnSpyEx/dnSpy#365]
### Problem Description

At the moment we can only search for references for all of the enum values. On a large enum this leads to massive amount of false positive search results.

### Proposal

Right click on an enum value and clicking on 'Analyze' should let us find all references where this specific enum value is being used.

### Alternatives

If there is an existing alternative I'm happy to use that but I haven't found any

**Comment by PercyDan54** [comment]
#50
