### ISSUE TITLE
Decompilation of function variables

### ISSUE THREAD

**Issue by adrmnv** [dnSpyEx/dnSpy#374]
### Description

Is there a way to fix this behavior, where all variables are assigned the name \u0020, that is, a space? When trying to change the code, the application gives an error, and reports that in all other methods, the names are exactly the same.
![image](https://github.com/user-attachments/assets/a3d7fefa-8c3a-449d-8422-4ae5d6696e13)

**Comment by GazziFX** [comment]
For obfuscated assemblies use de4dot

**Comment by ElektroKill** [comment]
Hello,

the parameter names in the picture contain obfuscated names. Please use a tool like de4dot to rename them into valid names so that the file can be edited.

**Comment by adrmnv** [comment]
> For obfuscated assemblies use de4dot


> Hello,
> 
> the parameter names in the picture contain obfuscated names. Please use a tool like de4dot to rename them into valid names so that the file can be edited.

de4dot breaks the file and it stops running, although it helps with renaming variables. what else can I do?

**Comment by greenozon** [comment]
get used to crazy names and continue to debug original bits :)
