### ISSUE TITLE
Can't set breakpoint on async code

### ISSUE THREAD

**Issue by idan-h** [dnSpyEx/dnSpy#378]
### dnSpyEx version

v6.5.1

### Describe the Bug

.NET 6, I have async code.

When I try to set a breakpoint in the code before I ran it, nothing happens. The breakpoint won't be added.
When I debug and step into the method, then it shows me different code - the state machine code of the async operation.

How do I see this before debugging? why do I see different code that I can't debug?

### How To Reproduce

Load some module with async code, go to the async method and try adding breakpoints.

### Expected Behavior

Add breakpoints

### Actual Behavior

Won't add a breakpoint

### Additional Context

f

**Comment by ElektroKill** [comment]
Hi,

This is probably occurring because you have this option enabled in dnSpy:
![image](https://github.com/user-attachments/assets/aeefbcae-d248-448f-9307-44938e9ebc94)

Enabling this option results in the debug info for the sync method being generated with regard to the original state machine as opposed to the lifted async code.

**Comment by idan-h** [comment]
> Hi,
> 
> This is probably occurring because you have this option enabled in dnSpy: ![image](https://private-user-images.githubusercontent.com/37494960/381273374-aeefbcae-d248-448f-9307-44938e9ebc94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMzAxMTMsIm5iZiI6MTczMDIyOTgxMywicGF0aCI6Ii8zNzQ5NDk2MC8zODEyNzMzNzQtYWVlZmJjYWUtZDI0OC00NDhmLTkzMDctNDQ5MzhlOWViYzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE5MjMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NmNkYjk4YWJmYjAzZTgyNzk4MWY5ZDlmNTJmYjEyMjllMDY4OTdlZGNjMWVmYzdlZjY2YzdjNTM2ZGQ0ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MBhbm9MGKNDX4CUuGgsICTFdVaxSDEeSsULx03wI0y8)
> 
> Enabling this option results in the debug info for the sync method being generated with regard to the original state machine as opposed to the lifted async code.

yea I think this is it haha.
Did this change from the old dnspy? because I remember you had to check this option to actually see the async code
