### ISSUE TITLE
Render obfuscated resource names as \u unicode chars

### ISSUE THREAD

**Issue by greenozon** [dnSpyEx/dnSpy#387]
### dnSpyEx version

6.5.1

### Describe the Bug

I'd like to ask if it's possible to print obfuscated resource names using \u sequences
for example as it does ILSPY:

![image](https://github.com/user-attachments/assets/85661e57-0e95-4432-9879-52d21f61fdcd)

### How To Reproduce

find some obfuscated asm 

### Expected Behavior

see above pic in the left hand

### Actual Behavior

see above pic to the right

### Additional Context

thank you!

**Comment by zuoyuanchun** [comment]
1.https://github.com/horsicq/Detect-It-Easy
2.https://github.com/SychicBoy/NETReactorSlayer
3.https://github.com/de4dot/de4dot
4.https://github.com/ipwnosx/de4dot-All-Version-2021
I think you should first understand the protective shell, and then try to unpack the software!
