### ISSUE TITLE
After Dnspy starting , a message is displayed indicating that debugging cannot be performed

### ISSUE THREAD

**Issue by Tomolddrive** [dnSpyEx/dnSpy#59]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
- 6.1.8
![1](https://user-images.githubusercontent.com/95367254/147331697-ba5319ce-1d56-427c-8093-a225adb9a346.png)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
- After startup, a popup window appears, as shown in the figure

**Comment by ElektroKill** [comment]
Hi,
Can you please change dnSpy language to English and then provide a screenshot of the pop up? I don’t understand that language sorry!

**Comment by Tomolddrive** [comment]
Theme

**Comment by Tomolddrive** [comment]
> Hi, Can you please change dnSpy language to English and then provide a screenshot of the pop up? I don’t understand that language sorry!

Theme。The mean Debug cannot start.

**Comment by ElektroKill** [comment]
Please provide screenshot of the error prompt in elvish language or provide the file you are trying to debug.

**Comment by PercyDan54** [comment]
Literally just do what it saids.
Start dnSpy with Admin privileges
![image](https://user-images.githubusercontent.com/50285552/147384014-46284d6f-a374-4bd5-9ac5-e22fb34a5007.png)

**Comment by Tomolddrive** [comment]
> 



> Literally just do what it saids. Start dnSpy with Admin privileges ![image](https://user-images.githubusercontent.com/50285552/147384014-46284d6f-a374-4bd5-9ac5-e22fb34a5007.png)

1111111111

**Comment by Tomolddrive** [comment]
> Literally just do what it saids. Start dnSpy with Admin privileges ![image](https://user-images.githubusercontent.com/50285552/147384014-46284d6f-a374-4bd5-9ac5-e22fb34a5007.png)

不可以，可能跟我设置有关，因为有些软件不要双击或者以管理员运行，因为我是用dnspy运行的，直接启动，但是会报错。不用Dnspy，运行软件没有问题。

**Comment by Tomolddrive** [comment]
> Literally just do what it saids. Start dnSpy with Admin privileges ![image](https://user-images.githubusercontent.com/50285552/147384014-46284d6f-a374-4bd5-9ac5-e22fb34a5007.png)

no,windowns system need to change,I have solved.

**Comment by ElektroKill** [comment]
@Tomolddrive Is this issue solved? If yes, then please close the issue :)
