### ISSUE TITLE
Update dnlib to latest avaiable source

### ISSUE THREAD

**Issue by Deltafox79** [dnSpyEx/dnSpy#6]
Hi,
Latest avaiable source for dnlib is date 11 Nov 2020

https://github.com/0xd4d/dnlib

can update repository for dnspyEx?

Regards

**Comment by ElektroKill** [comment]
Now that 0xd4d (wtfsck) released the latest changes as a new nuget update this shouldn’t be two hard to fix. Expect it in the next release!
