### ISSUE TITLE
Explorer icons are white

### ISSUE THREAD

**Issue by Nuklon** [dnSpyEx/dnSpy#66]
Since https://github.com/dnSpyEx/dnSpy/pull/14 the explorer icons are white, which results in invisible DLL icons, and also dnSpy self.

- What version did you use? Any build since https://github.com/dnSpyEx/dnSpy/pull/14.

**Comment by ElektroKill** [comment]
Example on a Windows 8.1 VM:
![image](https://user-images.githubusercontent.com/37494960/151659012-ec32c8c8-81ba-442e-8414-2ffa983e5a00.png)

**Comment by ElektroKill** [comment]
Reopening as it seems that for some reason the new icons don't scale well in Windows Explorer. The size and bit depth is the same (128x128 32bit). 

Example:
![image](https://user-images.githubusercontent.com/37494960/164073318-5570b9e9-f0fa-4a4f-9fd8-aed00781c21f.png)
The new icon looks blocky and has jagged edges.
