### ISSUE TITLE
What's the difference between dnSpy-net-win64.zip and dnSpy-netframework.zip?

### ISSUE THREAD

**Issue by ianklatzco** [dnSpyEx/dnSpy#68]
(googled around, but couldn't find an answer)

On the releases page: https://github.com/dnSpyEx/dnSpy/releases/tag/v6.1.9

**Comment by ElektroKill** [comment]
`dnSpy-netframework.zip` is a build compiled to run on .NET Framework 4.8
`dnSpy-net-win64.zip` is a build compiled to run on .NET 5 64 bit version
`dnSpy-net-win32.zip` is a build compiled to run on .NET 5 32 bit version

**Comment by ianklatzco** [comment]
Does picking one of these releases limit which targets you can load into dnSpy?

**Comment by ianklatzco** [comment]
Based on dnSpy's UI, looks like 32b version is used for 32b applications.

**Comment by GazziFX** [comment]
There is no difference between NET Framework and NET 5 (also doesn't matter bitness) for inspecting and editing. For debugging bitness is matter, but I don't know if matters Runtime

**Comment by ElektroKill** [comment]
Exactly like @GazziFX mentioned, for inspecting and editing assembly the bitness or runtime doesn't matter at all. For debugging the bitness of dnSpy should match the bitness of the application being debugged. Runtime shouldn't make a difference for debugging. 

The only difference between .NET Framework and .NET 5 versions is the runtime itself and one tiny feature missing from .NET 5 versions. This feature is Windows shortcut file resolving for drag and drop. When you drag and drop a `.ink` file onto the assembly explorer in the .NET Framework version dnSpy will resolve the shortcut to the target file using a COM component and open that in the assembly explorer. This feature is unavailable in the .NET 5 version.

**Comment by ianklatzco** [comment]
Thanks!
