### ISSUE TITLE
Is there any way to change UI language?

### ISSUE THREAD

**Issue by krypt-lynx** [dnSpyEx/dnSpy#79]
I have have non-english windows version, so, looks like this version of dnSpy uses system language by default (unlike last from the original repo)
But I don't see any language settings on options menu. Did I missing something of there is actually no way to change UI language?

**Comment by krypt-lynx** [comment]
It was supposed to be an entry in discussions, Oh, well.

**Comment by ElektroKill** [comment]
Hi, there is an option to change the display language. You can find it by going to `View` -> `Langauge` -> `English` (or any other language you might want). After you change it just restart dnSpy and the language should be changed!

![image](https://user-images.githubusercontent.com/37494960/161398399-140538fb-7af9-4fea-af2a-48d5eefc2483.png)

**Comment by krypt-lynx** [comment]
Thanks! I gone directly to Options menu 🤦

**Comment by ElektroKill** [comment]
Can I close the issue now?

**Comment by krypt-lynx** [comment]
Yes.
I propose to duplicate it to options menu (well, I expected to find *all* of the options in where), but the question is already resolved. Thanks.
