### ISSUE TITLE
Decompiled code format problem

### ISSUE THREAD

**Issue by DATA-GaMi** [dnSpyEx/dnSpy#95]
Before clicking `Submit new issue`, try the latest build [![](https://github.com/dnSpyEx/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/dnSpyEx/dnSpy/actions)

- What version did you use?
dnspy 6.2.0
- Write down all steps needed to reproduce this issue. Also attach any needed files.

**The style of the code generated after decompilation is very strange, how to format the code?**

![CodeFormat](https://user-images.githubusercontent.com/48061253/175860577-1b47b6d7-7c12-4f6b-993f-ecc713c59049.png)

**Comment by GazziFX** [comment]
I've seen this before, this is because inspecting assembly was compiled in the Debug profile

**Comment by ElektroKill** [comment]
The `flag` local variables usually occur when decompiling debug builds as pointed out by @GazziFX. However, this file might be obfuscated with some sort of protection that injects additional local variables. Debug builds would usually only have one "level" of flag variable like shown in the example below:
```
bool flag1 = Console.ReadLine() == "test";
if (flag1) {
}
```
Your file however features something like this which I have not seen in debug builds and is probably an indication that this file was in some way obfuscated:
```
bool flag1 = Console.ReadLine() == "test";
bool flag2 = flag1;
if (flag2) {
}
```
The ILSpy 2.4 decompiler engine used by dnSpyEx does not currently do a good job at inlining unnecessary variables and hence this rather messy output is produced.

As for the big amount of `if-else` conditions, this is very likely just user code being that messy.

**Comment by DATA-GaMi** [comment]
okay.I'll try to change the decomplier engine version.
